### ISSUE TITLE
Exposed Django configuration file

### ISSUE THREAD

**Issue by hlesesne** [ordered-online/orders#1]
Potential security breach. See /orders/orders/settings.py

**Comment by PhilippMatthes** [comment]
This is no security breach. The only information, that could be used to breach into the system, is the secret key. In production, we provide the secret key from our private `.env` file.

Note: I suppose, this issue was created by a bot (see image).
<img width="814" alt="Bildschirmfoto 2019-11-05 um 09 59 30" src="https://user-images.githubusercontent.com/27271818/68193274-0fc04b00-ffb3-11e9-8d5e-1f424afa1ff6.png">
